# package : uam_route_planner
/**:
  ros__parameters:
    osm_file_name: "lg_tower_speed.osm"
    # short route
    # osm_file_name: "demo.osm" 

    # short route
    # osm_file_name: "fixed_control_tune.osm" 

    flight_altitude: 300.0 #constant UAM's flight altitude
    is_dense_waypoint : false

    interpolate_step: 1.0